FullSteel.mbm /c12..\..\title.bmp
/1..\..\titlem.bmp
/c12..\..\cdicon.bmp
/1..\..\cdiconm.bmp
/c12..\..\micicon.bmp
/1..\..\miciconm.bmp
/c12..\..\genre.bmp
/1..\..\genrem.bmp
/c12..\..\folder.bmp
/1..\..\folderm.bmp
/c12..\..\file.bmp
/1..\..\filem.bmp
/c12..\..\back.bmp
/1..\..\backm.bmp
/c12..\..\playing.bmp
/1..\..\playingm.bmp
/c12..\..\paused.bmp
/1..\..\pausedm.bmp
/c12..\..\flipclosed.bmp
/c16simple_steel_s60.bmp
/c12..\..\listboxfocus.bmp
/c12..\..\listboxfocusm.bmp
/c12volume.bmp
/1volumem.bmp
/c12..\..\volumefocus.bmp
/1..\..\volumefocusm.bmp
/c12slider.bmp
/1sliderm.bmp
/c12..\..\sliderfocus.bmp
/1..\..\sliderfocusm.bmp
/c12..\..\stop.bmp
/1..\..\stopm.bmp
/1..\..\stop_dimmed.bmp
/c12..\..\stopfocus.bmp
/c12..\..\play.bmp
/1..\..\playm.bmp
/1..\..\play_dimmed.bmp
/c12..\..\playfocus.bmp
/c12..\..\pause.bmp
/1..\..\pausem.bmp
/c12..\..\pausefocus.bmp
/c16oggplaylogo.bmp
/1oggplaylogom.bmp
