OggPlayP900.mbm /c12..\..\title.bmp
/1..\..\titlem.bmp
/c12..\..\cdicon.bmp 
/1..\..\cdiconm.bmp
/c12..\..\micicon.bmp
/1..\..\miciconm.bmp          
/c12..\..\genre.bmp
/1..\..\genrem.bmp
/c12..\..\folder.bmp
/1..\..\folderm.bmp
/c12..\..\file.bmp
/1..\..\filem.bmp
/c12..\..\back.bmp
/1..\..\backm.bmp
/c12..\..\playing.bmp
/1..\..\playingm.bmp
/c12..\..\paused.bmp      
/1..\..\pausedm.bmp
/c12..\..\flipclosed_p900.bmp
/c12..\..\flipopen_steel.bmp
/c12..\..\volume.bmp
/1..\..\volumem.bmp     
/1..\..\volumem.bmp
/c12..\..\repeat.bmp
/1..\..\repeatm.bmp
/c12..\..\slider.bmp
/1..\..\sliderm.bmp
/c12..\..\knob.bmp
/1..\..\knobm.bmp
/c12..\..\bar.bmp
/1..\..\barm.bmp
/c12..\..\stop.bmp
/1..\..\stopm.bmp
/1..\..\stop_dimmed.bmp
/c12..\..\play.bmp
/1..\..\playm.bmp
/1..\..\play_dimmed.bmp
/c12..\..\pause.bmp
/1..\..\pausem.bmp
/c12..\..\alarms.bmp
/1..\..\alarmsm.bmp
